set -g default-terminal 'tmux-256color'
set -g terminal-features 'xterm-256color:RGB'

# remap prefix from C-b to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# split panes
unbind '"'
unbind %
bind s split-window -h
bind v split-window -v

# reload config
bind r source-file ~/.config/tmux/tmux.conf

# disable mouse mode
set -g mouse off

# looksmaxxing

set -g status-justify left
set -g status-style 'fg=default'

set -g status-left ' '

set -g status-right '#[reverse bold] #S #[bg=color8 fg=default noreverse] #[fg=default]#h#[bg=default fg=color8] '

set -g window-status-format '#I #[fg=white bold]#W #[fg=yellow]#F'
set -g window-status-current-format '#[reverse bold] #I #W #[bg=color8 fg=default noreverse] #[fg=default]#F#[bg=default fg=color8] '

#  
